### ISSUE TITLE
proxy routes e.g. for static paths not in static/

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/edgerender-rust#15]
e.g. for returning `favicon.ico`

usage, something like 

```yaml
routes:
  - match: '/'
  - match: '/favicon.ico'
    proxy: '/static/favicon.ico'
```
